import type {Metadata} from "next";
import {astoria, cera} from "@/public/fonts/fonts";
import "./globals.css";
import React from "react";
import NavBar from "@/app/components/section/NavBar";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn("bg-background", "h-full", "antialiased", astoria.variable, cera.variable, "font-sans", geist.variable)}
        >
        <body className="min-h-full flex flex-col">
        <NavBar/>
        {children}
        </body>
        </html>
    );
}
